# Header
menu:
  Home: /
  About: /my-page/
  Notes: /archives/
#   Resume: /2024/01/19/b
# rss: /atom.xml
banner: "images/banner.jpg"

# Content
excerpt_link: Read More
fancybox: true

# # Footer
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Footer
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use html like below...
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Sidebar
sidebar: false
widgets: []
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# Widget behavior
archive_type: 'monthly'
show_count: false
recent_posts_limits: 2

# Miscellaneous
google_analytics: G-V61RBS882C
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info


# Resume
title: Reassume
resume:
  name: Ken Liang
  # jobtitle: Your Job Title
  location:
    # - key: address
    #   value: Your Address
    # - key: postalCode
    #   value: '510000'
    - key: city
      value: GuangZhou
    - key: region
      value: GuangDong
    - key: countryCode
      value: CN
  contact:
    - icon: fa-external-link
      text: https://kenleungsq.github.io
    - icon: fa-envelope
      text: kenliangsq@foxmail.com
    # - icon: fa-phone-square
    #   text: your-phone-num
  profiles:
    # - icon: fa-linkedin
    #   text: your-linkedin
    #   link: https://linkedin.com/
    # - icon: fa-github
    #   text: your-github
    #   link: https://github.com/
  overview: '1、 RPA:UiPath, UiPath Orchestrator, Power Platform(Power automate, Power Apps, SharePoint), pyautogui, playwright
<br>2、 Data related:Excel, PowerBI, Python (基础语法、numpy、pandas)
<br>3、 Program Language:C#, HTML, CSS, JS, VBA, Python
<br>4、 Website Development:Django, Vue, nodejs
<br>5、 Database:MySQL, SQL Server, Access
<br>6、 System:Windows, Linux 基本命令及操作
<br>7、 Container tech:docker
<br>8、 Server: Nginx'
  #   level: beginner, intermediate, advanced, master
  skills:
    - title: UiPath
      level: advanced
      items: [Studio, Ochestrator]
    - title: Python
      level: intermediate
      items: [Django, Pandas, Playwright]
    - title: Power Platform
      level: advanced
      items: [Power Automate, Power Apps, Share Point, Power BI]
  
# Showcase your work
  projects:
  - title: Resource and Project management webiste devlopment based on Python&VUE2&MySQL
    description: '1. The foudation of the system is earned value concept
<br>2. Perform development of a complete function both backend and frontend
<br>3. perform part database work such of foreign key design and table creation
<br>4.  perform part of the deployment work such as IIS, nginx, unicom'
    duration: Apr 2023 - Oct 2023
    contribution: Developer
  - title: SPOC of a famous express industry
    description: '1, Maintain different Power Automate flows(10+)
<br>2, Maintain a SharePoint list(tens of thousands rows of data)
<br>3, Estimate the feasibility of new requirement from customer
<br>4, Develop new Power Automate flows
<br>5, Regular meeting and Customer Care'
    duration: Mar 2023 - Oct 2023
    contribution: Solution Architect and Developer
# Langguages Known 
# proficiency: beginner, intermediate, advanced, master, fluent, native speaker
  languages:
  - name: Cantonese
    proficiency: native speaker
  - name: Mandarin
    proficiency: fluent
  - name: English
    proficiency: intermediate
